//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIS.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsTable
    {
        public int Id { get; set; }
        public Nullable<int> ScopeId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Enabled { get; set; }
        public string ClientName { get; set; }
        public string ClientSecret { get; set; }
        public string RedirectUrl { get; set; }
        public string LogoutRedirectUrl { get; set; }
        public string Description { get; set; }
        public string Logo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual Scope Scope { get; set; }
    }
}
