//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIS.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrisEntities : DbContext
    {
        public PrisEntities()
            : base("name=PrisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<App> Apps { get; set; }
        public virtual DbSet<ClientsTable> ClientsTables { get; set; }
        public virtual DbSet<PublishApp> PublishApps { get; set; }
        public virtual DbSet<Scope> Scopes { get; set; }
    }
}
