//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRIS.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublishApp
    {
        public int Id { get; set; }
        public Nullable<int> AppId { get; set; }
        public string Source { get; set; }
        public string Description { get; set; }
        public string AllowedUsers { get; set; }
        public string QueryKeywords { get; set; }
        public string ReportTypes { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> Publisher { get; set; }
    
        public virtual App App { get; set; }
    }
}
